### ISSUE TITLE
Tracker: Gdk Scaling

### ISSUE THREAD

**Issue by infirit** [blueman-project/blueman#716]
When using a scale factor of 2 (GDK_SCALE=2) we run into a few problems like blurry icons. Take for example the composite icons in the ManagerDevicelist. 

Everywhere we let Gtk handle icon loading they are scaled nicely but we tend to use pixbufs all over the place. The best solution would be to let Gtk handle the icons whenever possible. And where we manipulate icon pixbufs use cairo surfaces which supports scaling. The only problem is that these function are not yet available in a released pycairo version, see https://github.com/pygobject/pycairo/commit/498dc027a0ab067471392e1de0e472a77453a415.

I personally do not have a HiDPI display so would be nice if folks who do use these displays and scale comment with issues they see.

Feel free to add more items below.

- [x] Move away from using pixbufs in Gtk Widgets like menus (pr #712)
- [x] Use cairo surfaces to create composite icons, then use the surface directly in the CellRenderer
- [x] Decide what to do with our low quality device icons.

**Comment by infirit** [comment]
I found that Gtk already has scaling options when retrieving icons so we do not need to rely on the cairo commit.

The current status is that all the preparatory work has been done, the last bits in #729. When merged I'll prepare and clean up #719.

The main problem we have is that our device icons are low quality and we have no svg for them. So when we scale them it only gets worse. Unless we have an artist who is willing to help out this will remain a problem. The other option is to drop out device icons for the delivered icons from icon themes.

**Comment by infirit** [comment]
Finished the cairo surface work so the only item left is the low quality device icons we provide. I currently see three options:

* Keep using the low quality device icons
* Always use the icon property exposed by BlueZ dbus api
* Find an artist to make beautiful device icons for us (I am definitely not an artists)

**Comment by infirit** [comment]
This is done, the signal bar discussion can continue in #860
